jobs:
- name: upload-artifact-releaser-autopush-staging
  on_failure:
    file: guest-test-infra/concourse/tasks/publish-job-result.yaml
    task: failure
    vars:
      job: upload-artifact-releaser-autopush-staging
      pipeline: guest-package-build
      result_state: failure
      start_timestamp: ((.:start-timestamp-ms))
  on_success:
    file: guest-test-infra/concourse/tasks/publish-job-result.yaml
    task: success
    vars:
      job: upload-artifact-releaser-autopush-staging
      pipeline: guest-package-build
      result_state: success
      start_timestamp: ((.:start-timestamp-ms))
  plan:
  - get: guest-test-infra
  - file: guest-test-infra/concourse/tasks/generate-timestamp.yaml
    task: generate-timestamp
  - file: timestamp/timestamp-ms
    load_var: start-timestamp-ms
  - in_parallel:
      fail_fast: true
      steps:
      - file: guest-test-infra/concourse/tasks/gcloud-package-operation.yaml
        params:
          TOPIC: projects/artifact-releaser-autopush/topics/gcp-guest-package-upload-autopush
          TYPE: uploadToStaging
        task: upload-artifact-releaser-autopush-deb11
        vars:
          package_path: artifact-releaser/google-guest-agent_20211019.00-g1_amd64.deb
          repo: guest-arle-autopush-trusty
          universe: cloud-apt
      - file: guest-test-infra/concourse/tasks/gcloud-package-operation.yaml
        params:
          TOPIC: projects/artifact-releaser-autopush/topics/gcp-guest-package-upload-autopush
          TYPE: uploadToStaging
        task: upload-artifact-releaser-autopush-el7
        vars:
          package_path: artifact-releaser/google-guest-agent-20211019.00-g1.el8.x86_64.rpm
          repo: guest-arle-autopush-el7-x86_64
          universe: cloud-yum
      - file: guest-test-infra/concourse/tasks/gcloud-package-operation.yaml
        params:
          TOPIC: projects/artifact-releaser-autopush/topics/gcp-guest-package-upload-autopush
          TYPE: uploadToStaging
        task: upload-artifact-releaser-autopush-win
        vars:
          package_path: artifact-releaser/google-compute-engine-windows.x86_64.20211019.00.0@1.goo
          repo: guest-arle-autopush
          universe: cloud-yuck
- name: promote-artifact-releaser-autopush-stable
  on_failure:
    file: guest-test-infra/concourse/tasks/publish-job-result.yaml
    task: failure
    vars:
      job: promote-guest-agent-stable
      pipeline: guest-package-build
      result_state: failure
      start_timestamp: ((.:start-timestamp-ms))
  on_success:
    file: guest-test-infra/concourse/tasks/publish-job-result.yaml
    task: success
    vars:
      job: promote-guest-agent-stable
      pipeline: guest-package-build
      result_state: success
      start_timestamp: ((.:start-timestamp-ms))
  plan:
  - get: guest-test-infra
    passed:
    - upload-artifact-releaser-autopush-staging
  - file: guest-test-infra/concourse/tasks/generate-timestamp.yaml
    task: generate-timestamp
  - file: timestamp/timestamp-ms
    load_var: start-timestamp-ms
  - in_parallel:
      steps:
      - file: guest-test-infra/concourse/tasks/gcloud-promote-package.yaml
        params:
          TOPIC: projects/artifact-releaser-autopush/topics/gcp-guest-package-promote-autopush
        task: promote-deb11-stable
        vars:
          environment: stable
          repo: guest-arle-autopush-trusty
          universe: cloud-apt
      - file: guest-test-infra/concourse/tasks/gcloud-promote-package.yaml
        params:
          TOPIC: projects/artifact-releaser-autopush/topics/gcp-guest-package-promote-autopush
        task: promote-el7-stable
        vars:
          environment: stable
          repo: guest-arle-autopush-el7-x86_64
          universe: cloud-yum
      - file: guest-test-infra/concourse/tasks/gcloud-promote-package.yaml
        params:
          TOPIC: projects/artifact-releaser-autopush/topics/gcp-guest-package-promote-autopush
        task: promote-windows-stable
        vars:
          environment: stable
          repo: guest-arle-autopush
          universe: cloud-yuck
- name: artifact-releaser-publish-images-autopush
  on_failure:
    file: guest-test-infra/concourse/tasks/publish-job-result.yaml
    task: failure
    vars:
      job: promote-debian
      pipeline: guest-image-build
      result_state: failure
      start_timestamp: ((.:start-timestamp-ms))
  on_success:
    file: guest-test-infra/concourse/tasks/publish-job-result.yaml
    task: success
    vars:
      job: promote-debian
      pipeline: guest-image-build
      result_state: success
      start_timestamp: ((.:start-timestamp-ms))
  plan:
  - get: guest-test-infra
  - get: compute-image-tools
  - file: guest-test-infra/concourse/tasks/generate-timestamp.yaml
    task: generate-timestamp
  - file: timestamp/timestamp-ms
    load_var: start-timestamp-ms
  - task: generate-version
    file: guest-test-infra/concourse/tasks/generate-version.yaml
  - load_var: version
    file: publish-version/version
  - in_parallel:
      steps:
      - file: guest-test-infra/concourse/tasks/gcloud-publish-image.yaml
        task: publish-debian-10
        vars:
          topic: "projects/artifact-releaser-autopush/topics/gcp-guest-image-release-autopush"
          image_name: "debian_10"
          gcs_image_path: "gs://artifact-releaser-autopush-rtp/debian"
          wf: "debian/debian_10.publish.json"
          publish_version: ((.:version))
          source_version: "v20211027"
          release_notes: "Disregard this release. Debian 10 test."
      - file: guest-test-infra/concourse/tasks/gcloud-publish-image.yaml
        task: publish-almalinux-8
        vars:
          topic: "projects/artifact-releaser-autopush/topics/gcp-guest-image-release-autopush"
          image_name: "almalinux_8"
          gcs_image_path: "gs://artifact-releaser-autopush-rtp/almalinux"
          wf: "enterprise_linux/almalinux_8.publish.json"
          publish_version: ((.:version))
          source_version: "v20211027"
          release_notes: "Disregard this release. Alma Linux 8 test."
- name: release-testing-image-to-artifact-releaser-prod
  plan:
  - get: guest-test-infra
  - get: compute-image-tools
  - task: generate-version
    file: guest-test-infra/concourse/tasks/generate-version.yaml
  - load_var: version
    file: publish-version/version
  - file: guest-test-infra/concourse/tasks/gcloud-publish-image.yaml
    task: publish-prod-test
    vars:
      topic: "projects/artifact-releaser-prod/topics/gcp-guest-image-release-prod"
      image_name: "prod-publish-test"
      gcs_image_path: "gs://artifact-releaser-autopush-rtp/publish-prod-test"
      wf: "test-workflow.json"
      publish_version: ((.:version))
      source_version: "v20220511"
      release_notes: "Test release."
- name: test-workload-identity
  plan:
  - task: show-workload-identity
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: google/cloud-sdk
          tag: alpine
      run:
        path: /bin/sh
        args:
        - -exc
        - |
          curl -H Metadata-Flavor:Google http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/email

resources:
- name: guest-test-infra
  source:
    branch: master
    fetch_tags: true
    uri: https://github.com/GoogleCloudPlatform/guest-test-infra.git
  type: git
- name: compute-image-tools
  source:
    uri: https://github.com/GoogleCloudPlatform/compute-image-tools.git
    branch: master
  type: git
