---
resource_types:
- name: gcs
  type: registry-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: compute-image-tools
  type: git
  source:
    uri: https://github.com/GoogleCloudPlatform/compute-image-tools.git
    branch: master
- name: guest-test-infra
  type: git
  source:
    uri: https://github.com/GoogleCloudPlatform/guest-test-infra.git
    branch: master
- name: debian-10-worker-gcs
  type: gcs
  source:
    bucket: artifact-releaser-prod-rtp
    json_key: |
      ((gcs-key.credential))
    regexp: "debian-worker/debian-10-worker-v([0-9]+).tar.gz"

jobs:
# Build jobs
- name: build-debian-10-worker
  plan:
  - get: compute-image-tools
  - get: guest-test-infra
  - task: generate-timestamp
    file: guest-test-infra/concourse/tasks/generate-timestamp.yaml
  - load_var: start-timestamp-ms
    file: timestamp/timestamp-ms
  - task: generate-build-id
    file: guest-test-infra/concourse/tasks/generate-build-id.yaml
    vars:
      prefix: "debian-10-worker"
  - put: debian-10-worker-gcs
    params:
      file: build-id-dir/debian-10-worker*
    get_params:
      skip_download: "true"
  - load_var: gcs-url
    file: debian-10-worker-gcs/url
  - task: generate-build-date
    file: guest-test-infra/concourse/tasks/generate-version.yaml
  - load_var: build-date
    file: publish-version/version
  - task: daisy-build-debian-10-worker
    file: guest-test-infra/concourse/tasks/daisy-build-images-debian.yaml
    vars:
      wf: "debian/debian_10_worker.wf.json"
      gcs_url: ((.:gcs-url))
      google_cloud_repo: "stable"
      build_date: ((.:build-date))
  on_success:
    task: success
    file: guest-test-infra/concourse/tasks/publish-job-result.yaml
    vars:
      pipeline: "debian-worker-image-build"
      job: "build-debian-10-worker"
      result_state: "success"
      start_timestamp: ((.:start-timestamp-ms))
  on_failure:
    task: failure
    file: guest-test-infra/concourse/tasks/publish-job-result.yaml
    vars:
      pipeline: "debian-worker-image-build"
      job: "build-debian-10-worker"
      result_state: "failure"
      start_timestamp: ((.:start-timestamp-ms))
# Publish jobs
- name: publish-to-testing-debian-10-worker
  plan:
  - get: guest-test-infra
  - get: compute-image-tools
  - task: generate-timestamp
    file: guest-test-infra/concourse/tasks/generate-timestamp.yaml
  - load_var: start-timestamp-ms
    file: timestamp/timestamp-ms
  - get: debian-10-worker-gcs
    passed: [build-debian-10-worker]
    trigger: false
    params:
      skip_download: "true"
  - load_var: source-version
    file: debian-10-worker-gcs/version
  - task: generate-version
    file: guest-test-infra/concourse/tasks/generate-version.yaml
  - load_var: publish-version
    file: publish-version/version # produced from generate-version task
  - task: publish-debian-10-worker
    file: guest-test-infra/concourse/tasks/daisy-publish-images.yaml
    vars:
      source_gcs_path: "gs://artifact-releaser-prod-rtp/debian-worker"
      source_version: v((.:source-version))
      publish_version: ((.:publish-version))
      wf: "debian/debian_10_worker.publish.json"
      environment: "test"
  on_success:
    task: success
    file: guest-test-infra/concourse/tasks/publish-job-result.yaml
    vars:
      pipeline: "debian-worker-image-build"
      job: "publish-to-testing-debian-10-worker"
      result_state: "success"
      start_timestamp: ((.:start-timestamp-ms))
  on_failure:
    task: failure
    file: guest-test-infra/concourse/tasks/publish-job-result.yaml
    vars:
      pipeline: "debian-worker-image-build"
      job: "publish-to-testing-debian-10-worker"
      result_state: "failure"
      start_timestamp: ((.:start-timestamp-ms))
- name: publish-to-staging-debian-10-worker
  plan:
  - get: guest-test-infra
  - get: compute-image-tools
  - task: generate-timestamp
    file: guest-test-infra/concourse/tasks/generate-timestamp.yaml
  - load_var: start-timestamp-ms
    file: timestamp/timestamp-ms
  - get: debian-10-worker-gcs
    passed: [build-debian-10-worker]
    trigger: false
    params:
      skip_download: "true"
  - load_var: source-version
    file: debian-10-worker-gcs/version
  - task: generate-version
    file: guest-test-infra/concourse/tasks/generate-version.yaml
  - load_var: publish-version
    file: publish-version/version # produced from generate-version task
  - task: publish-debian-10-worker
    file: guest-test-infra/concourse/tasks/daisy-publish-images.yaml
    vars:
      source_gcs_path: "gs://artifact-releaser-prod-rtp/debian-worker"
      source_version: v((.:source-version))
      publish_version: ((.:publish-version))
      wf: "debian/debian_10_worker.publish.json"
      environment: "staging"
  on_success:
    task: success
    file: guest-test-infra/concourse/tasks/publish-job-result.yaml
    vars:
      pipeline: "debian-worker-image-build"
      job: "publish-to-staging-debian-10-worker"
      result_state: "success"
      start_timestamp: ((.:start-timestamp-ms))
  on_failure:
    task: failure
    file: guest-test-infra/concourse/tasks/publish-job-result.yaml
    vars:
      pipeline: "debian-worker-image-build"
      job: "publish-to-staging-debian-10-worker"
      result_state: "failure"
      start_timestamp: ((.:start-timestamp-ms))
- name: publish-to-prod-debian-10-worker
  plan:
  - get: guest-test-infra
  - get: compute-image-tools
  - task: generate-timestamp
    file: guest-test-infra/concourse/tasks/generate-timestamp.yaml
  - load_var: start-timestamp-ms
    file: timestamp/timestamp-ms
  - get: debian-10-worker-gcs
    passed: [publish-to-staging-debian-10-worker]
    trigger: false
    params:
      skip_download: "true"
  - load_var: source-version
    file: debian-10-worker-gcs/version
  - task: generate-version
    file: guest-test-infra/concourse/tasks/generate-version.yaml
  - load_var: publish-version
    file: publish-version/version # produced from generate-version task
  - task: publish-debian-10-worker
    file: guest-test-infra/concourse/tasks/gcloud-publish-image.yaml
    vars:
      source_gcs_path: "gs://artifact-releaser-prod-rtp/debian-worker"
      source_version: v((.:source-version))
      publish_version: ((.:publish-version))
      wf: "debian/debian_10_worker.publish.json"
      release_notes: ""
      image_name: "debian_10_worker"
      topic: "projects/artifact-releaser-prod/topics/gcp-guest-image-release-prod"
  on_success:
    task: success
    file: guest-test-infra/concourse/tasks/publish-job-result.yaml
    vars:
      pipeline: "debian-worker-image-build"
      job: "publish-to-prod-debian-10-worker"
      result_state: "success"
      start_timestamp: ((.:start-timestamp-ms))
  on_failure:
    task: failure
    file: guest-test-infra/concourse/tasks/publish-job-result.yaml
    vars:
      pipeline: "debian-worker-image-build"
      job: "publish-to-prod-debian-10-worker"
      result_state: "failure"
      start_timestamp: ((.:start-timestamp-ms))
