---
resource_types:
- name: gcs
  type: registry-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: compute-image-tools
  type: git
  source:
    uri: https://github.com/gaohannk/compute-image-tools.git
    branch: devcluster-image-build
- name: guest-test-infra
  type: git
  source:
    uri: https://github.com/gaohannk/guest-test-infra.git
    branch: devcluster-image-build
- name: debian-10-worker-gcs
  type: gcs
  source:
    bucket: gce-image-archive
    json_key: |
      ((gcs-key.credential))
    regexp: "debian-worker/debian-10-worker-v([0-9]+).tar.gz"
- name: centos-7-devcluster-gcs
  type: gcs
  source:
    bucket: gce-image-archive
    json_key: |
      ((gcs-key.credential))
    regexp: "devcluster/centos-7-dev-v([0-9]+).tar.gz"
- name: centos-8-devcluster-gcs
  type: gcs
  source:
    bucket: gce-image-archive
    json_key: |
      ((gcs-key.credential))
    regexp: "devcluster/centos-8-dev-v([0-9]+).tar.gz"
- name: debian-9-devcluster-gcs
  type: gcs
  source:
    bucket: gce-image-archive
    json_key: |
      ((gcs-key.credential))
    regexp: "devcluster/debian-9-dev-v([0-9]+).tar.gz"
- name: debian-10-devcluster-gcs
  type: gcs
  source:
    bucket: gce-image-archive
    json_key: |
      ((gcs-key.credential))
    regexp: "devcluster/debian-10-dev-v([0-9]+).tar.gz"
- name: debian-proxy-devcluster-gcs
  type: gcs
  source:
    bucket: gce-image-archive
    json_key: |
      ((gcs-key.credential))
    regexp: "devcluster/debian-9-proxy-v([0-9]+).tar.gz"
- name: ubuntu-1604-devcluster-gcs
  type: gcs
  source:
    bucket: gce-image-archive
    json_key: |
      ((gcs-key.credential))
    regexp: "devcluster/ubuntu-1604-dev-v([0-9]+).tar.gz"
- name: ubuntu-1804-devcluster-gcs
  type: gcs
  source:
    bucket: gce-image-archive
    json_key: |
      ((gcs-key.credential))
    regexp: "devcluster/ubuntu-1804-dev-v([0-9]+).tar.gz"

jobs:
# Build jobs
- name: build-debian-10-worker
  plan:
  - get: compute-image-tools
  - get: guest-test-infra
  - task: generate-build-id
    file: guest-test-infra/concourse/tasks/generate-build-id.yaml
    vars:
      prefix: "debian-10-worker"
  - put: debian-10-worker-gcs
    params:
      file: build-id-dir/debian-10-worker*
    get_params:
      skip_download: "true"
  - load_var: gcs-url
    file: debian-10-worker-gcs/url
  - task: generate-build-date
    file: guest-test-infra/concourse/tasks/generate-version.yaml
  - load_var: build-date
    file: publish-version/version
  - task: get-credential
    file: guest-test-infra/concourse/tasks/get-credential.yaml
  - task: daisy-build-debian-10-worker
    file: guest-test-infra/concourse/tasks/daisy-build-images-debian.yaml
    vars:
      wf: "debian/debian_10_worker.wf.json"
      gcs_url: ((.:gcs-url))
      google_cloud_repo: "stable"
      build_date: ((.:build-date))
- name: build-centos-7-devcluster
  plan:
  - get: compute-image-tools
  - get: guest-test-infra
  - task: generate-build-id
    file: guest-test-infra/concourse/tasks/generate-build-id.yaml
    vars:
      prefix: "centos-7-dev"
  - put: centos-7-devcluster-gcs
    params:
      file: build-id-dir/centos-7-dev*
    get_params:
      skip_download: "true"
  - load_var: gcs-url
    file: centos-7-devcluster-gcs/url
  - task: generate-build-date
    file: guest-test-infra/concourse/tasks/generate-version.yaml
  - load_var: build-date
    file: publish-version/version
  - task: get-credential
    file: guest-test-infra/concourse/tasks/get-credential.yaml
  - task: daisy-build-centos-7-devcluster
    file: guest-test-infra/concourse/tasks/daisy-build-images-dev.yaml
    vars:
      wf: "linux_devcluster/centos_7_devcluster.wf.json"
      build_date: ((.:build-date))
- name: build-centos-8-devcluster
  plan:
  - get: compute-image-tools
  - get: guest-test-infra
  - task: generate-build-id
    file: guest-test-infra/concourse/tasks/generate-build-id.yaml
    vars:
      prefix: "centos-8-dev"
  - put: centos-8-devcluster-gcs
    params:
      file: build-id-dir/centos-8-dev*
    get_params:
      skip_download: "true"
  - load_var: gcs-url
    file: centos-8-devcluster-gcs/url
  - task: generate-build-date
    file: guest-test-infra/concourse/tasks/generate-version.yaml
  - load_var: build-date
    file: publish-version/version
  - task: get-credential
    file: guest-test-infra/concourse/tasks/get-credential.yaml
  - task: daisy-build-centos-8-devcluster
    file: guest-test-infra/concourse/tasks/daisy-build-images-dev.yaml
    vars:
      wf: "linux_devcluster/centos_8_devcluster.wf.json"
      build_date: ((.:build-date))
- name: build-debian-9-devcluster
  plan:
  - get: compute-image-tools
  - get: guest-test-infra
  - task: generate-build-id
    file: guest-test-infra/concourse/tasks/generate-build-id.yaml
    vars:
      prefix: "debian-9-dev"
  - put: debian-9-devcluster-gcs
    params:
      file: build-id-dir/debian-9-dev*
    get_params:
      skip_download: "true"
  - load_var: gcs-url
    file: debian-9-devcluster-gcs/url
  - task: generate-build-date
    file: guest-test-infra/concourse/tasks/generate-version.yaml
  - load_var: build-date
    file: publish-version/version
  - task: get-credential
    file: guest-test-infra/concourse/tasks/get-credential.yaml
  - task: daisy-build-debian-9-devcluster
    file: guest-test-infra/concourse/tasks/daisy-build-images-dev.yaml
    vars:
      wf: "linux_devcluster/debian_9_devcluster.wf.json"
      build_date: ((.:build-date))
- name: build-debian-10-devcluster
  plan:
  - get: compute-image-tools
  - get: guest-test-infra
  - task: generate-build-id
    file: guest-test-infra/concourse/tasks/generate-build-id.yaml
    vars:
      prefix: "debian-10-dev"
  - put: debian-10-devcluster-gcs
    params:
      file: build-id-dir/debian-10-dev*
    get_params:
      skip_download: "true"
  - load_var: gcs-url
    file: debian-10-devcluster-gcs/url
  - task: generate-build-date
    file: guest-test-infra/concourse/tasks/generate-version.yaml
  - load_var: build-date
    file: publish-version/version
  - task: get-credential
    file: guest-test-infra/concourse/tasks/get-credential.yaml
  - task: daisy-build-debian-10-devcluster
    file: guest-test-infra/concourse/tasks/daisy-build-images-dev.yaml
    vars:
      wf: "linux_devcluster/debian_10_devcluster.wf.json"
      build_date: ((.:build-date))
- name: build-debian-proxy-devcluster
  plan:
  - get: compute-image-tools
  - get: guest-test-infra
  - task: generate-build-id
    file: guest-test-infra/concourse/tasks/generate-build-id.yaml
    vars:
      prefix: "debian-9-proxy"
  - put: debian-proxy-devcluster-gcs
    params:
      file: build-id-dir/debian-9-proxy*
    get_params:
      skip_download: "true"
  - load_var: gcs-url
    file: debian-proxy-devcluster-gcs/url
  - task: generate-build-date
    file: guest-test-infra/concourse/tasks/generate-version.yaml
  - load_var: build-date
    file: publish-version/version
  - task: get-credential
    file: guest-test-infra/concourse/tasks/get-credential.yaml
  - task: daisy-build-debian-proxy-devcluster
    file: guest-test-infra/concourse/tasks/daisy-build-images-dev.yaml
    vars:
      wf: "linux_devcluster/debian_proxy_devcluster.wf.json"
      build_date: ((.:build-date))
- name: build-ubuntu-1604-devcluster
  plan:
  - get: compute-image-tools
  - get: guest-test-infra
  - task: generate-build-id
    file: guest-test-infra/concourse/tasks/generate-build-id.yaml
    vars:
      prefix: "ubuntu-1604-dev"
  - put: ubuntu-1604-devcluster-gcs
    params:
      file: build-id-dir/ubuntu-1604-dev*
    get_params:
      skip_download: "true"
  - load_var: gcs-url
    file: ubuntu-1604-devcluster-gcs/url
  - task: generate-build-date
    file: guest-test-infra/concourse/tasks/generate-version.yaml
  - load_var: build-date
    file: publish-version/version
  - task: get-credential
    file: guest-test-infra/concourse/tasks/get-credential.yaml
  - task: daisy-build-ubuntu-1604-devcluster
    file: guest-test-infra/concourse/tasks/daisy-build-images-dev.yaml
    vars:
      wf: "linux_devcluster/ubuntu_1604_devcluster.wf.json"
      build_date: ((.:build-date))
- name: build-ubuntu-1804-devcluster
  plan:
  - get: compute-image-tools
  - get: guest-test-infra
  - task: generate-build-id
    file: guest-test-infra/concourse/tasks/generate-build-id.yaml
    vars:
      prefix: "ubuntu-1804-dev"
  - put: ubuntu-1804-devcluster-gcs
    params:
      file: build-id-dir/ubuntu-1804-dev*
    get_params:
      skip_download: "true"
  - load_var: gcs-url
    file: ubuntu-1804-devcluster-gcs/url
  - task: generate-build-date
    file: guest-test-infra/concourse/tasks/generate-version.yaml
  - load_var: build-date
    file: publish-version/version
  - task: get-credential
    file: guest-test-infra/concourse/tasks/get-credential.yaml
  - task: daisy-build-ubuntu-1804-devcluster
    file: guest-test-infra/concourse/tasks/daisy-build-images-dev.yaml
    vars:
      wf: "linux_devcluster/ubuntu_1804_devcluster.wf.json"
      build_date: ((.:build-date))

# Publish to dev stage
- name: publish-debian-staging
  plan:
  - get: guest-test-infra
  - get: compute-image-tools
  - get: debian-9-devcluster-gcs
    passed: [build-debian-9-devcluster]
    trigger: false
    params:
      skip_download: "true"
  - get: debian-10-devcluster-gcs
    passed: [build-debian-10-devcluster]
    trigger: false
    params:
      skip_download: "true"
  - load_var: source-version
    file: debian-9-devcluster-gcs/version
  - task: get-credential
    file: guest-test-infra/concourse/tasks/get-credential.yaml
  - task: generate-version
    file: guest-test-infra/concourse/tasks/generate-version.yaml
  - load_var: publish-version
    file: publish-version/version # produced from generate-version task
  - task: publish-debian-9-devcluster
    file: guest-test-infra/concourse/tasks/daisy-publish-images.yaml
    vars:
      source_gcs_path: "gs://gce-image-archive/devcluster"
      source_version: v((.:source-version))
      publish_version: ((.:publish-version))
      wf: "linux_devcluster/debian_staging.publish.json"
      environment: "test"

