---
resource_types:
- name: gcs
  type: registry-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: compute-image-tools
  type: git
  source:
    uri: https://github.com/gaohannk/compute-image-tools.git
    branch: devcluster-image-build
- name: guest-test-infra
  type: git
  source:
    uri: https://github.com/gaohannk/guest-test-infra.git
    branch: devcluster-image-build
- name: debian-10-worker-gcs
  type: gcs
  source:
    bucket: gce-image-archive
    json_key: |
      ((gcs-key.credential))
    regexp: "debian-worker/debian-10-worker-v([0-9]+).tar.gz"
- name: centos-7-dev-gcs
  type: gcs
  source:
    bucket: gce-image-archive
    json_key: |
      ((gcs-key.credential))
    regexp: "dev/centos-7-dev-v([0-9]+).tar.gz"
- name: centos-8-dev-gcs
  type: gcs
  source:
    bucket: gce-image-archive
    json_key: |
      ((gcs-key.credential))
    regexp: "dev/centos-8-dev-v([0-9]+).tar.gz"
- name: debian-9-dev-gcs
  type: gcs
  source:
    bucket: gce-image-archive
    json_key: |
      ((gcs-key.credential))
    regexp: "dev/debian-9-dev-v([0-9]+).tar.gz"
- name: debian-10-dev-gcs
  type: gcs
  source:
    bucket: gce-image-archive
    json_key: |
      ((gcs-key.credential))
    regexp: "dev/debian-10-dev-v([0-9]+).tar.gz"
- name: ubuntu-1604-dev-gcs
  type: gcs
  source:
    bucket: gce-image-archive
    json_key: |
      ((gcs-key.credential))
    regexp: "dev/ubuntu-1604-dev-v([0-9]+).tar.gz"
- name: ubuntu-1804-dev-gcs
  type: gcs
  source:
    bucket: gce-image-archive
    json_key: |
      ((gcs-key.credential))
    regexp: "dev/ubuntu-1804-dev-v([0-9]+).tar.gz"

jobs:
# Build jobs
- name: build-debian-10-worker
  plan:
  - get: compute-image-tools
  - get: guest-test-infra
  - task: generate-build-id
    file: guest-test-infra/concourse/tasks/generate-build-id.yaml
    vars:
      prefix: "debian-10-worker"
  - put: debian-10-worker-gcs
    params:
      file: build-id-dir/debian-10-worker*
    get_params:
      skip_download: "true"
  - load_var: gcs-url
    file: debian-10-worker-gcs/url
  - task: generate-build-date
    file: guest-test-infra/concourse/tasks/generate-version.yaml
  - load_var: build-date
    file: publish-version/version
  - task: get-credential
    file: guest-test-infra/concourse/tasks/get-credential.yaml
  - task: daisy-build-debian-10-worker
    file: guest-test-infra/concourse/tasks/daisy-build-images-debian.yaml
    vars:
      wf: "debian/debian_10_worker.wf.json"
      gcs_url: ((.:gcs-url))
      google_cloud_repo: "stable"
      build_date: ((.:build-date))
- name: build-centos-7-dev
  plan:
  - get: compute-image-tools
  - get: guest-test-infra
  - task: generate-build-id
    file: guest-test-infra/concourse/tasks/generate-build-id.yaml
    vars:
      prefix: "centos-7-dev"
  - put: centos-7-dev-gcs
    params:
      file: build-id-dir/centos-7-dev*
    get_params:
      skip_download: "true"
  - load_var: gcs-url
    file: centos-7-dev-gcs/url
  - task: generate-build-date
    file: guest-test-infra/concourse/tasks/generate-version.yaml
  - load_var: build-date
    file: publish-version/version
  - task: get-credential
    file: guest-test-infra/concourse/tasks/get-credential.yaml
  - task: daisy-build-centos-7-dev
    file: guest-test-infra/concourse/tasks/daisy-build-derivative-images.yaml
    vars:
      wf: "linux_dev/centos_7_dev.wf.json"
      gcs_url: ((.:gcs-url))
      build_date: ((.:build-date))
- name: build-centos-8-dev
  plan:
  - get: compute-image-tools
  - get: guest-test-infra
  - task: generate-build-id
    file: guest-test-infra/concourse/tasks/generate-build-id.yaml
    vars:
      prefix: "centos-8-dev"
  - put: centos-8-dev-gcs
    params:
      file: build-id-dir/centos-8-dev*
    get_params:
      skip_download: "true"
  - load_var: gcs-url
    file: centos-8-dev-gcs/url
  - task: generate-build-date
    file: guest-test-infra/concourse/tasks/generate-version.yaml
  - load_var: build-date
    file: publish-version/version
  - task: get-credential
    file: guest-test-infra/concourse/tasks/get-credential.yaml
  - task: daisy-build-centos-8-dev
    file: guest-test-infra/concourse/tasks/daisy-build-derivative-images.yaml
    vars:
      wf: "linux_dev/centos_8_dev.wf.json"
      gcs_url: ((.:gcs-url))
      build_date: ((.:build-date))
- name: build-debian-9-dev
  plan:
  - get: compute-image-tools
  - get: guest-test-infra
  - task: generate-build-id
    file: guest-test-infra/concourse/tasks/generate-build-id.yaml
    vars:
      prefix: "debian-9-dev"
  - put: debian-9-dev-gcs
    params:
      file: build-id-dir/debian-9-dev*
    get_params:
      skip_download: "true"
  - load_var: gcs-url
    file: debian-9-dev-gcs/url
  - task: generate-build-date
    file: guest-test-infra/concourse/tasks/generate-version.yaml
  - load_var: build-date
    file: publish-version/version
  - task: get-credential
    file: guest-test-infra/concourse/tasks/get-credential.yaml
  - task: daisy-build-debian-9-dev
    file: guest-test-infra/concourse/tasks/daisy-build-derivative-images.yaml
    vars:
      wf: "linux_dev/debian_9_dev.wf.json"
      gcs_url: ((.:gcs-url))
      build_date: ((.:build-date))
- name: build-debian-10-dev
  plan:
  - get: compute-image-tools
  - get: guest-test-infra
  - task: generate-build-id
    file: guest-test-infra/concourse/tasks/generate-build-id.yaml
    vars:
      prefix: "debian-10-dev"
  - put: debian-10-dev-gcs
    params:
      file: build-id-dir/debian-10-dev*
    get_params:
      skip_download: "true"
  - load_var: gcs-url
    file: debian-10-dev-gcs/url
  - task: generate-build-date
    file: guest-test-infra/concourse/tasks/generate-version.yaml
  - load_var: build-date
    file: publish-version/version
  - task: get-credential
    file: guest-test-infra/concourse/tasks/get-credential.yaml
  - task: daisy-build-debian-10-dev
    file: guest-test-infra/concourse/tasks/daisy-build-derivative-images.yaml
    vars:
      wf: "linux_dev/debian_10_dev.wf.json"
      gcs_url: ((.:gcs-url))
      build_date: ((.:build-date))
- name: build-ubuntu-1604-dev
  plan:
  - get: compute-image-tools
  - get: guest-test-infra
  - task: generate-build-id
    file: guest-test-infra/concourse/tasks/generate-build-id.yaml
    vars:
      prefix: "ubuntu-1604-dev"
  - put: ubuntu-1604-dev-gcs
    params:
      file: build-id-dir/ubuntu-1604-dev*
    get_params:
      skip_download: "true"
  - load_var: gcs-url
    file: ubuntu-1604-dev-gcs/url
  - task: generate-build-date
    file: guest-test-infra/concourse/tasks/generate-version.yaml
  - load_var: build-date
    file: publish-version/version
  - task: get-credential
    file: guest-test-infra/concourse/tasks/get-credential.yaml
  - task: daisy-build-ubuntu-1604-dev
    file: guest-test-infra/concourse/tasks/daisy-build-derivative-images.yaml
    vars:
      wf: "linux_dev/ubuntu_1604_dev.wf.json"
      gcs_url: ((.:gcs-url))
      build_date: ((.:build-date))
- name: build-ubuntu-1804-dev
  plan:
  - get: compute-image-tools
  - get: guest-test-infra
  - task: generate-build-id
    file: guest-test-infra/concourse/tasks/generate-build-id.yaml
    vars:
      prefix: "ubuntu-1804-dev"
  - put: ubuntu-1804-dev-gcs
    params:
      file: build-id-dir/ubuntu-1804-dev*
    get_params:
      skip_download: "true"
  - load_var: gcs-url
    file: ubuntu-1804-dev-gcs/url
  - task: generate-build-date
    file: guest-test-infra/concourse/tasks/generate-version.yaml
  - load_var: build-date
    file: publish-version/version
  - task: get-credential
    file: guest-test-infra/concourse/tasks/get-credential.yaml
  - task: daisy-build-ubuntu-1804-dev
    file: guest-test-infra/concourse/tasks/daisy-build-derivative-images.yaml
    vars:
      wf: "linux_dev/ubuntu_1804_dev.wf.json"
      gcs_url: ((.:gcs-url))
      build_date: ((.:build-date))

# Publish to dev stage
- name: publish-debian-staging
  plan:
  - get: guest-test-infra
  - get: compute-image-tools
  - get: debian-9-dev-gcs
    passed: [build-debian-9-dev]
    trigger: false
    params:
      skip_download: "true"
  - get: debian-10-dev-gcs
    passed: [build-debian-10-dev]
    trigger: false
    params:
      skip_download: "true"
  - load_var: source-version
    file: debian-9-dev-gcs/version
  - task: get-credential
    file: guest-test-infra/concourse/tasks/get-credential.yaml
  - task: generate-version
    file: guest-test-infra/concourse/tasks/generate-version.yaml
  - load_var: publish-version
    file: publish-version/version # produced from generate-version task
  - task: publish-debian-9-dev
    file: guest-test-infra/concourse/tasks/daisy-publish-images.yaml
    vars:
      source_gcs_path: "gs://gce-image-archive/dev"
      source_version: v((.:source-version))
      publish_version: ((.:publish-version))
      wf: "linux_dev/debian_staging.publish.json"
      environment: "test"

- name: publish-to-testing-debian-10-worker
  plan:
  - get: guest-test-infra
  - get: compute-image-tools
  - get: debian-10-worker-gcs
    passed: [build-debian-10-worker]
    trigger: false
    params:
      skip_download: "true"
  - load_var: source-version
    file: debian-10-worker-gcs/version
  - task: get-credential
    file: guest-test-infra/concourse/tasks/get-credential.yaml
  - task: generate-version
    file: guest-test-infra/concourse/tasks/generate-version.yaml
  - load_var: publish-version
    file: publish-version/version # produced from generate-version task
  - task: publish-debian-10-worker
    file: guest-test-infra/concourse/tasks/daisy-publish-images.yaml
    vars:
      source_gcs_path: "gs://gce-image-archive/debian-worker"
      source_version: v((.:source-version))
      publish_version: ((.:publish-version))
      wf: "debian/debian_10_worker.publish.json"
      environment: "test"
- name: publish-to-staging-debian-10-worker
  plan:
  - get: guest-test-infra
  - get: compute-image-tools
  - get: debian-10-worker-gcs
    passed: [publish-to-testing-debian-10-worker]
    trigger: false
    params:
      skip_download: "true"
  - load_var: source-version
    file: debian-10-worker-gcs/version
  - task: get-credential
    file: guest-test-infra/concourse/tasks/get-credential.yaml
  - task: generate-version
    file: guest-test-infra/concourse/tasks/generate-version.yaml
  - load_var: publish-version
    file: publish-version/version # produced from generate-version task
  - task: publish-debian-10-worker
    file: guest-test-infra/concourse/tasks/daisy-publish-images.yaml
    vars:
      source_gcs_path: "gs://gce-image-archive/debian-worker"
      source_version: v((.:source-version))
      publish_version: ((.:publish-version))
      wf: "debian/debian_10_worker.publish.json"
      environment: "staging"
- name: publish-to-prod-debian-10-worker
  plan:
  - get: guest-test-infra
  - get: compute-image-tools
  - get: debian-10-worker-gcs
    passed: [publish-to-staging-debian-10-worker]
    trigger: false
    params:
      skip_download: "true"
  - load_var: source-version
    file: debian-10-worker-gcs/version
  - task: get-credential
    file: guest-test-infra/concourse/tasks/get-credential.yaml
  - task: generate-version
    file: guest-test-infra/concourse/tasks/generate-version.yaml
  - load_var: publish-version
    file: publish-version/version # produced from generate-version task
  - task: publish-debian-10-worker
    file: guest-test-infra/concourse/tasks/daisy-publish-images.yaml
    vars:
      source_gcs_path: "gs://gce-image-archive/debian-worker"
      source_version: v((.:source-version))
      publish_version: ((.:publish-version))
      wf: "debian/debian_10_worker.publish.json"
      environment: "prod"