---
resources:
- name: guest-test-infra
  type: git
  source:
    uri: https://github.com/GoogleCloudPlatform/guest-test-infra.git
    branch: master

jobs:
- name: set-pipelines
  plan:
  - get: guest-test-infra
    trigger: true
  - set_pipeline: linux-image-build
    file: guest-test-infra/concourse/pipelines/linux-image-build.yaml
  - set_pipeline: guest-package-build
    file: guest-test-infra/concourse/pipelines/guest-package-build.yaml
  - set_pipeline: debian-worker-image-build
    file: guest-test-infra/concourse/pipelines/debian-worker-image-build.yaml
  - set_pipeline: bare-metal-image-build
    file: guest-test-infra/concourse/pipelines/bare-metal-image-build.yaml
  - set_pipeline: partner-image-export
    file: guest-test-infra/concourse/pipelines/partner-image-export.yaml
  - set_pipeline: windows-image-build
    file: guest-test-infra/concourse/pipelines/windows-image-build.yaml
