---
resources:
- name: guest-test-infra
  type: git
  source:
    uri: https://github.com/GoogleCloudPlatform/guest-test-infra.git
    branch: master

jobs:
- name: set-pipelines
  plan:
  - get: guest-test-infra
    trigger: true
  - set_pipeline: linux-image-build
    file: guest-test-infra/concourse/pipelines/linux-image-build.yaml
  - set_pipeline: guest-package-build
    file: guest-test-infra/concourse/pipelines/guest-package-build.yaml
  - set_pipeline: dev-image-build
    file: guest-test-infra/concourse/pipelines/dev-image-build.yaml
  - set_pipeline: bare-metal-image-build
    file: guest-test-infra/concourse/pipelines/bare-metal-image-build.yaml