jobs:
- name: manual-trigger
  plan:
  - get: cds-image
    trigger: false
  - get: rhua-image
    trigger: false
- name: deploy-staging-us-west1
  plan:
  - get: cds-image
    passed: [manual-trigger]
    trigger: true
  - get: rhua-image
    passed: [manual-trigger]
    trigger: true
  - config:
      image_resource:
        source:
          repository: google/cloud-sdk
          tag: alpine
        type: registry-image
      platform: linux
      run:
        args:
        - compute
        - instance-groups
        - managed
        - rolling-action
        - replace
        - --quiet
        - rhua-mig-staging-us-west1
        - --region=us-west1
        - --project=google.com:rhel-infra
        path: gcloud
    task: deploy-rhua
  - config:
      image_resource:
        source:
          repository: google/cloud-sdk
          tag: alpine
        type: registry-image
      platform: linux
      run:
        args:
        - compute
        - instance-groups
        - managed
        - wait-until
        - --version-target-reached
        - --quiet
        - rhua-mig-staging-us-west1
        - --region=us-west1
        - --project=google.com:rhel-infra
        path: gcloud
    task: wait-rhua
  - config:
      image_resource:
        source:
          repository: google/cloud-sdk
          tag: alpine
        type: registry-image
      platform: linux
      run:
        args:
        - compute
        - instance-groups
        - managed
        - rolling-action
        - replace
        - --quiet
        - cds-mig-staging-us-west1
        - --region=us-west1
        - --project=google.com:rhel-infra
        path: gcloud
    task: deploy-cds
  - config:
      image_resource:
        source:
          repository: google/cloud-sdk
          tag: alpine
        type: registry-image
      platform: linux
      run:
        args:
        - compute
        - instance-groups
        - managed
        - wait-until
        - --version-target-reached
        - --quiet
        - cds-mig-staging-us-west1
        - --region=us-west1
        - --project=google.com:rhel-infra
        path: gcloud
    task: wait-cds
- name: wave-1
  plan:
  - get: cds-image
    passed:
    - deploy-staging-us-west1
    trigger: true
  - get: rhua-image
    passed:
    - deploy-staging-us-west1
    trigger: true
- name: deploy-prod-europe-west1
  plan:
  - get: cds-image
    passed:
    - wave-1
    trigger: true
  - get: rhua-image
    passed:
    - wave-1
    trigger: true
  - config:
      image_resource:
        source:
          repository: google/cloud-sdk
          tag: alpine
        type: registry-image
      platform: linux
      run:
        args:
        - compute
        - instance-groups
        - managed
        - rolling-action
        - replace
        - --quiet
        - rhua-mig-prod-europe-west1
        - --region=europe-west1
        - --project=google.com:rhel-infra
        path: gcloud
    task: deploy-rhua
  - config:
      image_resource:
        source:
          repository: google/cloud-sdk
          tag: alpine
        type: registry-image
      platform: linux
      run:
        args:
        - compute
        - instance-groups
        - managed
        - wait-until
        - --version-target-reached
        - --quiet
        - rhua-mig-prod-europe-west1
        - --region=europe-west1
        - --project=google.com:rhel-infra
        path: gcloud
    task: wait-rhua
  - config:
      image_resource:
        source:
          repository: google/cloud-sdk
          tag: alpine
        type: registry-image
      platform: linux
      run:
        args:
        - compute
        - instance-groups
        - managed
        - rolling-action
        - replace
        - --quiet
        - cds-mig-prod-europe-west1
        - --region=europe-west1
        - --project=google.com:rhel-infra
        path: gcloud
    task: deploy-cds
  - config:
      image_resource:
        source:
          repository: google/cloud-sdk
          tag: alpine
        type: registry-image
      platform: linux
      run:
        args:
        - compute
        - instance-groups
        - managed
        - wait-until
        - --version-target-reached
        - --quiet
        - cds-mig-prod-europe-west1
        - --region=europe-west1
        - --project=google.com:rhel-infra
        path: gcloud
    task: wait-cds
- name: deploy-prod-us-central1
  plan:
  - get: cds-image
    passed:
    - wave-1
    trigger: true
  - get: rhua-image
    passed:
    - wave-1
    trigger: true
  - config:
      image_resource:
        source:
          repository: google/cloud-sdk
          tag: alpine
        type: registry-image
      platform: linux
      run:
        args:
        - compute
        - instance-groups
        - managed
        - rolling-action
        - replace
        - --quiet
        - rhua-mig-prod-us-central1
        - --region=us-central1
        - --project=google.com:rhel-infra
        path: gcloud
    task: deploy-rhua
  - config:
      image_resource:
        source:
          repository: google/cloud-sdk
          tag: alpine
        type: registry-image
      platform: linux
      run:
        args:
        - compute
        - instance-groups
        - managed
        - wait-until
        - --version-target-reached
        - --quiet
        - rhua-mig-prod-us-central1
        - --region=us-central1
        - --project=google.com:rhel-infra
        path: gcloud
    task: wait-rhua
  - config:
      image_resource:
        source:
          repository: google/cloud-sdk
          tag: alpine
        type: registry-image
      platform: linux
      run:
        args:
        - compute
        - instance-groups
        - managed
        - rolling-action
        - replace
        - --quiet
        - cds-mig-prod-us-central1
        - --region=us-central1
        - --project=google.com:rhel-infra
        path: gcloud
    task: deploy-cds
  - config:
      image_resource:
        source:
          repository: google/cloud-sdk
          tag: alpine
        type: registry-image
      platform: linux
      run:
        args:
        - compute
        - instance-groups
        - managed
        - wait-until
        - --version-target-reached
        - --quiet
        - cds-mig-prod-us-central1
        - --region=us-central1
        - --project=google.com:rhel-infra
        path: gcloud
    task: wait-cds
- name: deploy-prod-asia-southeast1
  plan:
  - get: cds-image
    passed:
    - wave-1
    trigger: true
  - get: rhua-image
    passed:
    - wave-1
    trigger: true
  - config:
      image_resource:
        source:
          repository: google/cloud-sdk
          tag: alpine
        type: registry-image
      platform: linux
      run:
        args:
        - compute
        - instance-groups
        - managed
        - rolling-action
        - replace
        - --quiet
        - rhua-mig-prod-asia-southeast1
        - --region=asia-southeast1
        - --project=google.com:rhel-infra
        path: gcloud
    task: deploy-rhua
  - config:
      image_resource:
        source:
          repository: google/cloud-sdk
          tag: alpine
        type: registry-image
      platform: linux
      run:
        args:
        - compute
        - instance-groups
        - managed
        - wait-until
        - --version-target-reached
        - --quiet
        - rhua-mig-prod-asia-southeast1
        - --region=asia-southeast1
        - --project=google.com:rhel-infra
        path: gcloud
    task: wait-rhua
  - config:
      image_resource:
        source:
          repository: google/cloud-sdk
          tag: alpine
        type: registry-image
      platform: linux
      run:
        args:
        - compute
        - instance-groups
        - managed
        - rolling-action
        - replace
        - --quiet
        - cds-mig-prod-asia-southeast1
        - --region=asia-southeast1
        - --project=google.com:rhel-infra
        path: gcloud
    task: deploy-cds
  - config:
      image_resource:
        source:
          repository: google/cloud-sdk
          tag: alpine
        type: registry-image
      platform: linux
      run:
        args:
        - compute
        - instance-groups
        - managed
        - wait-until
        - --version-target-reached
        - --quiet
        - cds-mig-prod-asia-southeast1
        - --region=asia-southeast1
        - --project=google.com:rhel-infra
        path: gcloud
    task: wait-cds
resource_types:
- name: registry-image-private
  source:
    repository: gcr.io/compute-image-tools/registry-image-forked
  type: registry-image
- name: gce-img
  source:
    google_auth: true
    repository: gcr.io/gcp-guest/gce-img-resource
  type: registry-image-private
resources:
- name: cds-image
  source:
    family: cds
    project: google.com:rhel-infra
  type: gce-img
- name: rhua-image
  source:
    family: rhua
    project: google.com:rhel-infra
  type: gce-img
