jobs:
- name: sap-workload-test
  plan:
  - get: sap-hana-post-script-gcs
    trigger: false
  - task: generate-post-script
    config:
      platform: linux
      type: docker-image
      source:
        repository: google/cloud-sdk
        tag: latest
      run:
        path: sh
        args:
        - -exc
        - |
          # TODO - versioning/id. Want to map these logs for the check-post-script-results task
          cat <<EOT >>sap_post_script.sh
          if cat /var/log/messages | grep -q "ERROR - Deployment Exited"; then
            echo "ERROR" > result.txt
          else
            echo "SUCCESS" > result.txt
          fi
          gsutil cp result.txt gs://test-bucket-for-terraform/run_result.txt
          EOT

          gsutil cp sap_post_script.sh gs://test-bucket-for-terraform/sap_post_script.sh

  - task: run-sap-tf-environment
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: hashicorp/terraform
          tag: latest
      run:
        path: sh
        args:
        - -exc
        - |
          cat <<EOT >> sap_hana.tf
          module "sap_hana" {
          source = "https://storage.googleapis.com/cloudsapdeploy/terraform/latest/terraform/sap_hana/sap_hana_module.zip"
          project_id = "pneil-sandbox"
          zone = "us-east1-b"
          machine_type = "n1-highmem-32"
          subnetwork = "default"
          linux_image = "rhel-8-4-sap-ha"
          linux_image_project = "rhel-sap-coud"
          instance_name = "hana-instance"
          post_deployment_script = "gs://test-bucket-for-terraform/sap_post_script.sh"
          }
          EOT

          terraform init -upgrade
          terraform apply -auto-approve
          terraform destroy -auto-approve

  - task: check-post-script-results
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: google/cloud-sdk
          tag: latest
      run:
        path: sh
        args:
        - -exc
        - |
          gsutil cat gs://test-bucket-for-terraform/run_result.txt | grep -q "SUCCESS"


resources:
- name: sap-hana-post-script-gcs
  type: gcs
  source:
    bucket: test-bucket-for-terraform
    json_key: |
      ((gcs-key.credential))
