steps:
  - name: 'gcr.io/cloud-builders/go'
    dir: './autoversioner'
    args: ['install', './cmd/...']
    env: ['PROJECT_ROOT=github.com/GoogleCloudPlatform/guest-test-infra']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/autoversioner:latest', '--tag=gcr.io/$PROJECT_ID/autoversioner:$COMMIT_SHA', '.']
    dir: './autoversioner'

images:
  - 'gcr.io/$PROJECT_ID/autoversioner:latest'
  - 'gcr.io/$PROJECT_ID/autoversioner:$COMMIT_SHA'

