options:
  env:
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org
  volumes:
    - name: go-modules
      path: /go
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/gocheck:latest', '--tag=gcr.io/$PROJECT_ID/gocheck:$COMMIT_SHA', './container_images/gocheck']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/gobuild:latest', '--tag=gcr.io/$PROJECT_ID/gobuild:$COMMIT_SHA', './container_images/gobuild']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/gotest:latest', '--tag=gcr.io/$PROJECT_ID/gotest:$COMMIT_SHA', './container_images/gotest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/daisy-builder:latest', '--tag=gcr.io/$PROJECT_ID/daisy-builder:$COMMIT_SHA', './container_images/daisy-builder']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/selinux-tools:latest', '--tag=gcr.io/$PROJECT_ID/selinux-tools:$COMMIT_SHA', './container_images/selinux-tools']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/build-essential:latest', '--tag=gcr.io/$PROJECT_ID/build-essential:$COMMIT_SHA', './container_images/build-essential']
- name: 'golang:1.12'
  dir: './autoversioner/cmd/versiongenerator'
  args: ["go","build","-o","/workspace/bin/versiongenerator","main.go"]
- name: 'golang:1.12'
  dir: './autoversioner/cmd/tagger'
  args: ["go","build","-o","/workspace/bin/tagger","main.go"]
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/autoversioner:latest', '--file=./container_images/autoversioner/Dockerfile', "/workspace"]
images:
  - 'gcr.io/$PROJECT_ID/gocheck:latest'
  - 'gcr.io/$PROJECT_ID/gocheck:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/gobuild:latest'
  - 'gcr.io/$PROJECT_ID/gobuild:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/gotest:latest'
  - 'gcr.io/$PROJECT_ID/gotest:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/daisy-builder:latest'
  - 'gcr.io/$PROJECT_ID/daisy-builder:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/selinux-tools:latest'
  - 'gcr.io/$PROJECT_ID/selinux-tools:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/build-essential:latest'
  - 'gcr.io/$PROJECT_ID/build-essential:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/autoversioner:latest'
  - 'gcr.io/$PROJECT_ID/autoversioner:$COMMIT_SHA'