steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/gocheck:latest', '--tag=gcr.io/$PROJECT_ID/gocheck:$COMMIT_SHA', './container_images/gocheck']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/gobuild:latest', '--tag=gcr.io/$PROJECT_ID/gobuild:$COMMIT_SHA', './container_images/gobuild']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/gotest:latest', '--tag=gcr.io/$PROJECT_ID/gotest:$COMMIT_SHA', './container_images/gotest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/daisy-builder:latest', '--tag=gcr.io/$PROJECT_ID/daisy-builder:$COMMIT_SHA', './container_images/daisy-builder']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/build-essential:latest', '--tag=gcr.io/$PROJECT_ID/build-essential:$COMMIT_SHA', './container_images/build-essential']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/autoversioner:latest', '--tag=gcr.io/$PROJECT_ID/autoversioner:$COMMIT_SHA', '--file=./container_images/autoversioner/Dockerfile', "/workspace"]
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/concourse-metrics:latest', '--tag=gcr.io/$PROJECT_ID/concourse-metrics:$COMMIT_SHA', '--file=./container_images/concourse-metrics/Dockerfile', "/workspace"]
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/flake8:latest', '--tag=gcr.io/$PROJECT_ID/flake8:$COMMIT_SHA', './container_images/flake8']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/gointegtest:latest', '--tag=gcr.io/$PROJECT_ID/gointegtest:$COMMIT_SHA', './container_images/gointegtest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/pytest:latest', '--tag=gcr.io/$PROJECT_ID/pytest:$COMMIT_SHA', './container_images/pytest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/fly-validate-pipelines:latest', '--tag=gcr.io/$PROJECT_ID/fly-validate-pipelines:$COMMIT_SHA', './container_images/fly-validate-pipelines']
images:
  - 'gcr.io/$PROJECT_ID/gocheck:latest'
  - 'gcr.io/$PROJECT_ID/gocheck:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/gobuild:latest'
  - 'gcr.io/$PROJECT_ID/gobuild:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/gotest:latest'
  - 'gcr.io/$PROJECT_ID/gotest:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/daisy-builder:latest'
  - 'gcr.io/$PROJECT_ID/daisy-builder:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/build-essential:latest'
  - 'gcr.io/$PROJECT_ID/build-essential:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/autoversioner:latest'
  - 'gcr.io/$PROJECT_ID/autoversioner:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/flake8:latest'
  - 'gcr.io/$PROJECT_ID/flake8:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/gointegtest:latest'
  - 'gcr.io/$PROJECT_ID/gointegtest:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/pytest:latest'
  - 'gcr.io/$PROJECT_ID/pytest:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/fly-validate-pipelines:latest'
  - 'gcr.io/$PROJECT_ID/fly-validate-pipelines:$COMMIT_SHA'
