---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: certbot/dns-google

inputs:
- name: credentials
- name: gcp-secret-manager

outputs:
- name: tls-output

params:

run:
  path: sh
  args:
  - -exc
  - |
    # Generating a CSR is the best way to bypass certbot's usual behavior and just get a cert.
    openssl req \
      -key $PWD/gcp-secret-manager/rhui_tls_key \
      -subj "/O=Google Compute Engine/CN=rhui.googlecloud.com" \
      -addext "subjectAltName = DNS:rhui.googlecloud.com" \
      -addext "subjectAltName = DNS:staging-rhui.googlecloud.com" \
      -out rhui.csr
    certbot certonly \
      --manual \
      # Email to associate with cert, for rotations/revocations.
      --email "bigcluster-guest-team@google.com" \
      --no-eff-email
      # The input and output values.
      --csr $PWD/rhui.csr \
      --key-path $PWD/gcp-secret-manager/rhui_tls_key \
      --cert-path $PWD/tls-output/rhui.crt \
      # Using ACME dns-01 and our public ACME endpoint.
      --preferred-challenges "dns-01" \
      --server "https://dv.acme-v02.api.pki.goog/directory" \
      --eab-kid `cat gcp-secret-manager/eab-kid` \
      --eab-hmac-key `cat gcp-secret-manager/eab-hmac-key` \
      # Using dns-google plugin to automatically satisfy dns-01 challenge.
      --dns-google \
      --dns-google-credentials $PWD/credentials/credentials.json
