platform: linux

image_resource:
  type: docker-image
  source:
    repository: gcr.io/compute-image-tools/daisy
    tag: release

inputs:
- name: compute-image-tools
- name: credentials
- name: publish-version

params:
  GOOGLE_APPLICATION_CREDENTIALS: "credentials/credentials.json"

run:
  path: /daisy
  args:
  - -project=gcp-guest
  - -zone=us-central1-c
  - -var:source_image=((source-image))
  - -var:gcs_package_path=((gcs-package-path))
  - -var:dest_image=((dest-image))
  - ./compute-image-tools/daisy_workflows/image_build/install_package/install_package.wf.json
