platform: linux

image_resource:
  type: docker-image
  source:
    repository: gcr.io/compute-image-tools/daisy
    tag: latest

inputs:
- name: compute-image-tools
- name: credentials

params:
  GOOGLE_APPLICATION_CREDENTIALS: "credentials/credentials.json"

run:
  path: /daisy
  args:
  - -project=gce-image-builder
  - -zone=us-central1-c
  - -var:installer_iso=((iso))
  - -var:build_date=((build_date))
  - -var:google_cloud_repo=((google_cloud_repo))
  - -var:gcs_url=((gcs_url))
  - -var:workflow_root=../../
  - -compute_endpoint_override=https://www.googleapis.com/compute/beta/projects/
  - ./compute-image-tools/daisy_workflows/build-publish/((wf))
