platform: linux

image_resource:
  type: docker-image
  source:
    repository: gcr.io/compute-image-tools/daisy
    tag: latest

inputs:
- name: compute-image-tools
- name: credentials
- name: publish-version

params:
  GOOGLE_APPLICATION_CREDENTIALS: "credentials/credentials.json"

run:
  path: /daisy
  args:
  - -project=gce-image-builder
  - -zone=us-central1-c
  - -var:build_date=((build_date))
  - -var:gcs_url=((gcs_url))
  - -var:sql_server_media=((sql_server_media))
  - -var:source_image_project=((source_image_project))
  - -var:ssms_exe=((ssms_exe))
  - -var:timeout=((timeout))
  - -compute_endpoint_override=https://www.googleapis.com/compute/beta/projects/
  - ./compute-image-tools/daisy_workflows/build-publish/((wf))
