platform: linux

image_resource:
  type: registry-image
  source:
    repository: gcr.io/compute-image-tools/daisy
    tag: release

inputs:
- name: compute-image-tools

run:
  path: /daisy
  args:
  - -project=gcp-guest
  - -zone=us-central1-a
  - -DefaultTimeout=20m
  - -var:source_image=((source-image))
  - -var:gcs_package_path=((gcs-package-path))
  - -var:dest_image=((dest-image))
  - -var:machine_type=((machine-type))
  - -var:worker_image=((worker-image))
  - ./compute-image-tools/daisy_workflows/image_build/install_package/install_package.wf.json
