---
platform: linux

image_resource:
  type: docker-image
  source: {repository: gcr.io/hanga-testing/gce_image_publish-with-creds, tag: latest}

inputs:
- name: workflows

run:
  path: /gce_image_publish
  args:
  - -source_gcs_path=((gcs_path))
  - -noRoot
  - -source_version=((source_version))
  - -publish_version=((publish_version))
  - -filter=((family))
  - -skip_confirmation
  - -work_project=liamh-testing
  - -publish_project=liamh-testing
  - workflows/((wf))