platform: linux

image_resource:
  type: docker-image
  source:
    repository: google/cloud-sdk
    tag: alpine

inputs:
- name: credentials

params:
  GOOGLE_APPLICATION_CREDENTIALS: "credentials/credentials.json"
  TOPIC_PKG_PROMOTE_AUTOPUSH: "projects/artifact-releaser-autopush/topics/gcp-guest-package-promote-autopush"

run:
  path: sh
  args:
  - -exc
  - |
    gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
    gcloud pubsub topics publish $TOPIC_PKG_PROMOTE_AUTOPUSH --message '{"type": "promote", "request": {"universe": "((universe))", "repo": "((repo))", "environment": "((environment))"}}'
    