---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: google/cloud-sdk
    tag: alpine

# TYPE can be set to be "uploadToUnstable", "uploadToStaging", or "promoteToStaging"
params:
  TOPIC: "projects/artifact-releaser-prod/topics/gcp-guest-package-upload-prod"
  TYPE: "uploadToUnstable"

run:
  path: sh
  args:
  - -exc
  - |
    paths=$(echo "((package_path))" | tr ";" "\n")
    for path in $paths
    do
      if [[ "${objects}" != "" ]]; then
        objects="${objects}, "
      fi
      objects="${objects}{\"bucket\":\"gcp-guest-package-uploads\",\"object\":\"${path}\"}"
    done
    
    gcloud pubsub topics publish $TOPIC --message "{\"type\": \"${TYPE}\", \"request\": {\"bucket\": \"gcp-guest-package-uploads\", \"gcsfiles\": [${objects}], \"universe\": \"((universe))\", \"repo\": \"((repo))\"}}"
