---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: google/cloud-sdk
    tag: alpine

params:
  TOPIC: "projects/artifact-releaser-prod/topics/gcp-guest-package-promote-prod"

run:
  path: sh
  args:
  - -exc
  - |
    gcloud pubsub topics publish $TOPIC --message '{"type": "promote", "request": {"universe": "((universe))", "repo": "((repo))", "environment": "((environment))"}}'
