---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: google/cloud-sdk
    tag: alpine

inputs:
- name: credentials

params:
  GOOGLE_APPLICATION_CREDENTIALS: "credentials/credentials.json"
  TOPIC: "projects/artifact-releaser-prod/topics/gcp-guest-package-upload-prod"

run:
  path: sh
  args:
  - -exc
  - |
    gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
    gcloud pubsub topics publish $TOPIC --message '{"type": "uploadToUnstable", "request": {"bucket": "gcp-guest-package-uploads", "object": "((package_path))", "universe": "((universe))", "repo": "((repo))"}}'
