---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: google/cloud-sdk
    tag: latest

inputs:
- name: credentials

# let's start with this..
params:
  GOOGLE_APPLICATION_CREDENTIALS: "credentials/credentials.json"

run:
  path: sh
  args:
  - -exc
  - |
    gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
    # TODO: take topic and bucket?
    gcloud pubsub topics publish gcp-guest-package-uploads --message '{"type": "inject", "msg": {"bucket": "gcp-guest-package-uploads", "object": "((package_path))", "universe": "((universe))", "repo": "((repo))"}}'
