---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: busybox

outputs:
- name: build-id-dir-sbom

run:
  path: sh
  args:
  - -exc
  - "buildid=((id)); uuid=$(date '+%s'); echo $buildid | tee build-id-dir-sbom/build-id-sbom; touch build-id-dir-sbom/((prefix))-v${buildid}-${uuid}.sbom.json"
