---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox

outputs:
- name: build-id-dir

run:
  path: sh
  args:
  - -exc
  - "buildid=$(date '+%s'); echo $buildid | tee build-id-dir/build-id; touch build-id-dir/((prefix))-v${buildid}.tar.gz"