---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: google/cloud-sdk
    tag: alpine

outputs:
- name: generate-hash

run:
  path: sh
  args:
  - -exc
  - "gcloud storage cp ((gcsimgfile)) img.tar.gz; if [ $? != 0 ]; then exit 1; fi; echo $(sha256sum img.tar.gz) | tee generate-hash/hash"
