---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox

outputs:
- name: publish-version

run:
  path: sh
  args:
  - -exc
  - "date '+%Y%m%d' | tee publish-version/version"