---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: bash

outputs:
- name: timestamp

run:
  path: /usr/local/bin/bash
  args:
  - -c
  - "timestamp=$((${EPOCHREALTIME/./}/1000)); echo $(($timestamp/1000)) | tee timestamp/timestamp; echo $timestamp | tee timestamp/timestamp-ms"
