---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox

outputs:
- name: timestamp

run:
  path: sh
  args:
  - -exc
  - "timestamp=$(date '+%s%N'); echo $(($timestamp/1000000000)) | tee timestamp/timestamp; echo $(($timestamp/1000000)) > timestamp/timestamp-ms"