---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox

outputs:
- name: timestamp

run:
  path: sh
  args:
  - -exc
  - "timestamp=$(date '+%s'); echo $timestamp | tee timestamp/timestamp"