---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox

outputs:
- name: credentials

run:
  path: sh
  args:
  - -ec
  - |
    echo '((concourse-sa.credential))' > credentials/credentials.json
    ls credentials/credentials.json
