---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox

outputs:
- name: token

run:
  path: sh
  args:
  - -ec
  - |
    echo '((github-token.token))' > token/token.txt
    ls token/token.txt
