---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: gcr.io/gcp-guest/gotest
    tag: latest

inputs:
- name: repo

outputs:
- name: gotest

params:
  ARTIFACTS: ./gotest/

run:
  path: /main.sh
  args:
  - repo
