platform: linux

image_resource:
  type: registry-image
  source:
    repository: gcr.io/compute-image-tools/daisy

inputs:
- name: guest-test-infra

run:
  path: /daisy
  args:
  - -project=gcp-guest
  - -zone=us-west1-a
  - -var:repo_owner=GoogleCloudPlatform
  - -var:repo_name=((repo-name))
  - -var:git_ref=((git_ref))
  - -var:version=((version))
  - -var:gcs_path=((gcs_path))
  - -var:build_dir=
  - guest-test-infra/packagebuild/workflows/((wf))
