platform: linux

image_resource:
  type: docker-image
  source:
    repository: gcr.io/gcp-guest/cloud-image-tests
    tag: latest

inputs:
- name: guest-test-infra

run:
  path: /manager
  args:
  - -project=gcp-guest
  - -zone=us-west1-a
  - -test_projects=compute-image-test-pool-002,compute-image-test-pool-003,compute-image-test-pool-004,compute-image-test-pool-005
  - -exclude=oslogin
  - -images=((images))
