---
platform: linux

image_resource:
  type: registry-image-private
  source:
    repository: gcr.io/gcp-guest/concourse-metrics
    google_auth: true

run:
  path: /publish-coverage
  args:
  - --metric-path=golang/coverage/percent
  - --package-name=((package_name))
  - --coverage=((coverage_percent))
  - --project-id=gcp-guest
