---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: gcr.io/gcp-guest/concourse-metrics

run:
  path: /publish-job-result
  args:
  - --project-id=gcp-guest
  - --zone=us-west1-a
  - --pipeline=((pipeline))
  - --job=((job))
  - --task=publish-job-result
  - --result-state=((result_state))
  - --start-timestamp=((start_timestamp))
  - --metric-path=concourse/job/duration
