---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: gcr.io/gcp-guest/concourse-metrics
    tag: latest

inputs:
- name: credentials

params:
  GOOGLE_APPLICATION_CREDENTIALS: "credentials/credentials.json"

run:
  path: /publish-coverage
  args:
  - --metric-path=golang/coverage/percent
  - --package-name=((package_name))
  - --coverage=((coverage_percent))
  - --project-id=gcp-guest
