platform: linux

image_resource:
  type: docker-image
  source:
    repository: gcr.io/gcp-guest/validate-e2etest
    tag: latest

inputs:
- name: credentials
- name: guest-test-infra

params:
  GOOGLE_APPLICATION_CREDENTIALS: "credentials/credentials.json"
  GCS_PATH: gs://gcp-guest-e2e-test-outputs/((timestamp))
  GCS_URL: https://storage.cloud.google.com/gcp-guest-e2e-test-outputs/((timestamp))

run:
  # TODO validate e2e test result stored in GCS
  path: /validate-result.sh