platform: linux

image_resource:
  type: registry-image
  source:
    repository: gcr.io/gcp-guest/validate-integtest

inputs:
- name: guest-test-infra

params:
  GCS_PATH: gs://gcp-guest-test-outputs/((timestamp))
  GCS_URL: https://storage.cloud.google.com/gcp-guest-test-outputs/((timestamp))
  PACKAGE_NAME: ((repo-name))

run:
  path: /validate-result.sh
